### ISSUE TITLE
Jinc2D for chroma

### ISSUE THREAD

**Issue by aufkrawall** [zachsaw/MPDN_Extensions#102]
It would be very nice if we could use this algorithm also for chroma scaling.

**Comment by zachsaw** [comment]
Splitting NNEDI3 for chroma request to its own issue #110.

**Comment by zachsaw** [comment]
Jinc2D Chroma is done - https://github.com/zachsaw/MPDN_Extensions/commit/9b8caf8de921e8e5d6bea2980eff6f39974f725d
