### ISSUE TITLE
Add as a default program

### ISSUE THREAD

**Issue by Ryrynz** [zachsaw/MPDN_Extensions#117]
Allow MPDN to show up in Windows default programs list for associations.

**Comment by Belphemur** [comment]
It is the case of you use the installer. 

I did have it on Windows 8.1 and have it configured on Windows 10.

On 5 August 2015 04:29:48 EEST, Ryan <notifications@github.com> wrote:
>Allow MPDN to show up in Windows default programs list for
>associations.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zachsaw/MPDN_Extensions/issues/117

-- 
Best Regards, 
Antoine Aflalo

**Comment by Shiandow** [comment]
Closing this since it's pretty much the same as #84.
