### ISSUE TITLE
[UpdateChecker] Simple mode - some changes

### ISSUE THREAD

**Issue by zachsaw** [zachsaw/MPDN_Extensions#128]
Changes required:
1) Form needs to be centered on parent
2) Relaunch MPDN automatically after update
3) Extensions should only get installed for the current edition of MPDN (in case the other edition is old and can't run the new extensions) - this probably needs to be the case too for the advanced-mode updater

**Comment by Belphemur** [comment]
1. Can you explain me how to do this ? Or in which file I can find a piece of code for that ?
1. More complicate than expected.
    1. MPDN can be playing a file and would need to be reopen with the file (not difficult) but...
    1. Installer use Admin Right, it would relaunch MPDN as admin and that is not a good idea.
    1. It would need major changes to the installer to use something like this: http://nsis.sourceforge.net/UAC_plug-in . But as explained here: https://stackoverflow.com/questions/2414991/how-to-launch-a-program-as-as-a-normal-user-from-a-uac-elevated-installer doesn't work flawlessly ...
1. See #115, this was my idea for adding a Minimum requirement for the Extension Installer. It would need also to modify slightly the building process of the Extension to add that min version.
    1. Normal UseCase: Installer check the file version of MPDN against Min version.
    1. Updating UseCase: Installer check the MPDN_VERSION given against the Min version.

Thoughts ?

**Comment by zachsaw** [comment]
2. Just check the start MPDN check box via a command line switch. Click finish and mpdn will start. No need to resume playback.
3. Just unselect the other edition in the install options by default via command line switch too.

**Comment by zachsaw** [comment]
Hmm it's 2 & 3 but mark down renumbered them to 1 & 2.

**Comment by zachsaw** [comment]
Hmm the existing option to start MPDN after installation seems to run it in elevated mode too. But there are plenty of other installers that do the same. Maybe we should just leave this out and I'll get rid of that option in MPDN Installer too. Thoughts?

**Comment by Belphemur** [comment]
I was thinking that exactly. 
Nsis unfortunately doesn't support natively dynamic elevated mode.... 

After all there is the shortcut on the desktop. 

On 7 August 2015 06:51:21 EEST, Zach Saw <notifications@github.com> wrote:
>Hmm the existing option to start MPDN after installation seems to run
>it in elevated mode too. But there are plenty of other installers that
>do the same. Maybe we should just leave this out and I'll get rid of
>that option in MPDN Installer too. Thoughts?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zachsaw/MPDN_Extensions/issues/128#issuecomment-128583452

-- 
Best Regards, 
Antoine Aflalo

**Comment by Belphemur** [comment]
Btw can you clarify the 3) in your answer, I have difficulty to see the relation to my answer.

**Comment by zachsaw** [comment]
Oh I meant there's no need to do any versioning yet. My original number 3 is only asking for extensions to be updated for the launched player architecture, rather than updating both editions.

**Comment by Belphemur** [comment]
aah that simple, this is already done: https://github.com/zachsaw/MPDN_Extensions/blob/b96211fcffaf3ae181ebff96de820b2b000a4dff/Installer/Installer.nsi#L273-L284

In case arguments are given the installer select automatically which extension architecture to install.
