### ISSUE TITLE
[RendererControl] settings not restored

### ISSUE THREAD

**Issue by Shiandow** [zachsaw/MPDN_Extensions#142]
To reproduce: open any media, change the levels, and exit the player. Any media opened after that will use the same colorimetrics instead of reverting to automatic.

The cause seems to be that PlayerStateChanged doesn't get called on exit. This should either be fixed in MPDN itself or worked around in the player extension.

**Comment by zachsaw** [comment]
I think it'd more appropriate to fix it in MPDN itself. I'll do that for the next release. I haven't had a look at the code but I think I know why the event doesn't fire when application is exiting.

**Comment by zachsaw** [comment]
Can you test this with test build 3370 to see if it's indeed fixed?
http://mpdn.zachsaw.com/Test%20Builds/3370/

**Comment by Shiandow** [comment]
That seems to have fixed it.

**Comment by zachsaw** [comment]
BTW, don't use the new APIs yet - it's still a work in progress.

**Comment by Shiandow** [comment]
Hmm, I'm still encountering this problem occasionally.

I fear the problem occurs when MPDN crashes before the settings are restored. Although only if the settings were saved in the meantime. This makes it kind of hard to reproduce though.

**Comment by zachsaw** [comment]
Hmm I think I know why. I need to fix that in MPDN.

**Comment by zachsaw** [comment]
Can you check if this has been fixed with MPDN build 3380 with the above commit?

**Comment by Shiandow** [comment]
I think it's fixed now. Even when the process is stopped in debug mode (which should give MPDN no chance for recovery) it doesn't occur anymore.

**Comment by Shiandow** [comment]
Still seems to occur in some form. No known way to reproduce it yet.

[Description by aufkrawall](http://forum.doom9.org/showthread.php?p=1737002#post1737002):
>With the latest MPDN versions, I also noticed that video input colorimetric often sets itself to PC BT.601 and improve chroma reconstruction turns itself off. I suppose this randomly happens when changing other settings.

**Comment by Ryrynz** [comment]
Yes, I noticed this last night too. I thought this was set default, but after deleting settings it changed back to automatic and I couldn't get it to change back. I'll see if I can replicate it.

**Comment by Ryrynz** [comment]
Duplicated it easy enough. From a fresh profile enter the options press escape or okay and re-enter the options page. Color range and Chroma reconstruction are changed.

**Comment by zachsaw** [comment]
Found the problem. `m_OriginalOutputLevels` and `m_OriginalImproveChroma` weren't initialised to the configured values. Will be fixed in a bit.
