### ISSUE TITLE
Error when trying to create conditional filters

### ISSUE THREAD

**Issue by lunik1** [zachsaw/MPDN_Extensions#151]
On Windows 8.1 x64 I get the following error on all MPDN versions when trying to create a conditional filter:

> Retrieving the COM class factory for component with CLSID {78A51822-51F4-11D0-8F20-00805F2CD064} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).

**Comment by Shiandow** [comment]
Can anyone reproduce this problem?

**Comment by zachsaw** [comment]
Nope. It's a problem with the user's registry. Process debug manager COM interface isn't available likely due to corrupt registry.
