### ISSUE TITLE
Show current scale chain in OSD

### ISSUE THREAD

**Issue by zachsaw** [zachsaw/MPDN_Extensions#157]
This can be done via player extension and perhaps getting IFilter to return some texts describing what the filter is currently doing.

**Comment by zachsaw** [comment]
@Shiandow Thoughts?

**Comment by Shiandow** [comment]
Hmm, you could use the description of the renderscript. But in the end that's not really a description of what it's currently doing, but more what it is supposed to be doing.

Perhaps adding a "Status" property would help? Although allowing arbitrary strings would get messy pretty quickly, for most situations a simple "Active", "Inactive", "Broken" would be fine. Only for more complicated things like Script Chain you'd want something more flexible. I suppose you could make a "Status" class with "Active", "Inactive" and "Broken" as static instances, and a "Custom" subclass.

And then you'd need to figure out a good way to convert them to strings ("Custom" should probably just print some string verbatim, but the others should at least mention the script name).

**Comment by zachsaw** [comment]
I was thinking "Status" would simply return `string.Empty` when it's inactive and RenderChainScript could simply skip it when the status strings are aggregated. "Broken" should be communicated differently since it usually means an exception has occurred and we currently already have a mechanism for this via the player's debug OSD.

**Comment by Shiandow** [comment]
Fair enough. Although I just realised that it might be rather hard to find out if a renderscript is actually active though. Things like chroma scalers can be overruled by a chroma scaler later in the chain...

By the way I think "Status" should probably be a property of the RenderChain, since the RenderChainUi won't necessarily know what's happening.

**Comment by zachsaw** [comment]
Hmm how quickly could you make the changes to just have the basic status property to IFilter and RenderChain (and aggregating the IFilter.Status)? You could probably make the IFilter abstract classes return a default string.empty for now and I can do the rest.

**Comment by Shiandow** [comment]
Hmm I think it'd be pretty doable to check if a filter is active, which is all the status information you'd need probably. 

Then I think you could do something like "Status = () => Filter.Active ? "Active" : "" ". It's not the nicest looking way, but it'd work.

I'll see if I can make a quick commit with those changes.

**Comment by zachsaw** [comment]
I think we need a little more than that - namely a friendly name for the filter.
Perhaps `Status = () => Filter.Active ? Filter.Description : string.Empty`?

**Comment by Shiandow** [comment]
Yeah I wasn't planning on making a Status for the whole Filter chain though, that would probably get too complicated.

It'd probably be more informative if the RenderChains were responsible for reporting their status (possibly conditional on whether a Filter is active).

**Comment by zachsaw** [comment]
Ah that makes sense.

**Comment by Shiandow** [comment]
Okay I've made something which should work reasonably well. There are quite a few details that still need to be filled in, but it's getting late.

**Comment by zachsaw** [comment]
Thanks! I'll take over.

**Comment by zachsaw** [comment]
Alright. I've got most of it done.
The only thing left that I would want to see implemented is the comments I have left in RenderChainScript.cs `Update()`.

**Comment by Shiandow** [comment]
I'm declaring this feature complete: :-)
