### ISSUE TITLE
Opening VIDEO_TS.IFO doesn't load dvd

### ISSUE THREAD

**Issue by skcihmit** [zachsaw/MPDN_Extensions#167]
Hi,

I can't play DVD's using MPDN. I try opening VIDEO_TS.IFO and get the error failed to render file.
Is there some other way to play DVD's?

**Comment by Shiandow** [comment]
That's not really an issue with the extensions, and I'm not confident it could be fixed with an extension.

You should post this issue to the [doom9 MPDN player thread](http://forum.doom9.org/showthread.php?t=171120).
