### ISSUE TITLE
Add "scaling factor" as a supported keyword for render script conditionals

### ISSUE THREAD

**Issue by aufkrawall** [zachsaw/MPDN_Extensions#169]
Having this keyword would have many advantages over using source- and target size parameters for scaling:
-nothing to calculate for the user
-no nasty special cases to consider
-can achieve the same result with much less used conditionals
-can be shared between different display configurations (and thus users)
-easy to understand

**Comment by Shiandow** [comment]
Hmm, the current implementation of the Script properties is a bit weird, it doesn't reference the *current* size at all, but uses that size to determine if scaling is needed.

For clarity would you want "SourceSize" to refer to the video size or the current size? And which sizes would you like the "NeedsUpscaling", "NeedsDownscaling" and the scaling factors to refer to?

**Comment by aufkrawall** [comment]
I'm not sure I'm getting you right. :)
I would want it to work just like the checkboxes of image doubling options in madVR.
"if upscaling factor >= 1.5x, use scaling algorythm xyz"

**Comment by Shiandow** [comment]
Well, put it like this, say you use the following chain:

NNEDI3
Conditional (if ScalingFactor > 2 use NEDI)

If the input is say 240p, then after NNEDI3 it is 480p. If the target size is 720p should the conditional activate?

**Comment by aufkrawall** [comment]
I don't think so, as the target size after NNEDI3 wouldn't be >2x per axis if it's 480p -> 720p.

**Comment by Shiandow** [comment]
Yeah that's what I was thinking. But the way it's built now "SourceSize" would still indicate 240p, and there's no way to find out that it's already been scaled to 480p.

**Comment by Shiandow** [comment]
Okay you should be able to use "ScalingFactor" now. There's also ScalingFactorX and ScalingFactorY for the width and height separately, but those shouldn't usually be necessary.
