### ISSUE TITLE
[Framework] Generalize RenderChains to AudioScripts

### ISSUE THREAD

**Issue by Shiandow** [zachsaw/MPDN_Extensions#170]
It would be nice if RenderChains could be generalized to make it possible to use Script Chain and Script Groups (and similar meta render scripts) for AudioScripts it would.

Original discussion [here](https://github.com/zachsaw/MPDN_Extensions/commit/39e672b31e32ca85b5f9adb5a3e83dc357676fae#commitcomment-13355667).

**Comment by Shiandow** [comment]
Last comment of previous discussion:

---

I think resharper can take care of the renaming. At least, I noticed it's capable of finding derived names and will change those as well. So that part might be easier than you think.

By the way, an alternative would be to simply leave out the prefix "Render" for the general classes.

E.g. something like:

    Chain<T>
    AudioChain : Chain<IMediaSample>
    RenderChain : Chain<IFilter>

Or, if we combine the IFilter types:

    Chain<T> : where T : IFilter<IBaseType>
    AudioChain : Chain<IAudioFilter>
    RenderChain : Chain<IVideoFilter>

That aside, there are some difference between the AudioScript and RenderScript, which might make it difficult to treat them in a common way. 

Firstly there doesn't seem to be an equivalent to IRenderScriptUi for AudioScripts, but that should be easy enough to remedy. 

Secondly the IAudioScript is quite a bit different from the IRenderScript. The "Process()" and "Render()" methods are similar enought, but where IRenderScript has a method "Update()" which is called whenever something changes, IAudioScript has *several* callbacks depending on what changes. Might be better to generalize Update() or simplify the IAudioScript methods. Things would also be easier if they can be made more similar, but at the very least they'd need to have a common ancestor.

To make it possible to give them a common UI class I think you'd need a structure like:

    IScript { ... }
    IRenderScript : IScript { ... }
    IAudioScript : IScript { ... }

    IScriptUi<out IScript> : IExtensionUi
    {
         IScript CreateScript();
    }

    IRenderScriptUi : IScriptUi<IRenderScript> { }
    IAudioScriptUi : IScriptUi<IAudioScript> { }

The "IRenderScriptUi" and "IAudioScriptUi" are basically just aliases (which unfortunately don't exist in c#), so they aren't strictly necessary, but it's probably best to add them for clarity (although that means you can't have just one generic class which implements both IRenderScriptUi and IAudioScriptUi, which is a shame)

**Comment by zachsaw** [comment]
I'll create a branch and a test build for this.

**Comment by zachsaw** [comment]
This is now available in the APILevel8 branch: https://github.com/zachsaw/MPDN_Extensions/tree/APILevel8

I removed Mpdn.AudioChain since I suspect a lot of it would need to be rewritten anyway so there's really no point for me to make it compatible with API level 8.

**Comment by Shiandow** [comment]
Okay, I'd already made some changes to the framework to make things easier. One problem I still haven't quite solved is that AudioChains either have a method "void Process()" or "bool Process(AudioParam input, AudioParam output) but you really want something like "AudioParam Process(AudioParam input)". Is there any reason that you didn't write it that way?

Anyway I'll have a look at it this weekend, see if I can get things to work.

**Comment by zachsaw** [comment]
It needs a `bool` return type to indicate if `Process` is successful. When it's not, we need to fallback to the unprocessed audio samples. The original `Mpdn.AudioChain` replicates this behaviour by copying to temporary MediaSamples. Eventually this goes back to `bool Execute()`, and returning false causes MPDN to do a passthrough from input straight to output.

**Comment by Shiandow** [comment]
Is it that common for processing to fail? I mean, we could just make a "RenderChainScript" like wrapper to take care of exception handling, we're going to need one anyway if we want to merge the two UIs together.

**Comment by zachsaw** [comment]
Ah, false is also returned when the script isn't active but there's really no need to keep the method signature the way I've written it. Feel free to change it.

**Comment by Shiandow** [comment]
The "TExtensionClass" is making things a bit difficult, any objection to replacing it with a simple string property?

**Comment by Shiandow** [comment]
Should you be able to return "null" as an IScript? Because in that case "IScriptUi<TScript>" should force "TScript" to be nullable. If you don't do this it's very hard to make a general "nop" script.

It would also be nice if you could figure out a general way to get all scripts of type "TScript", that's necessary to generalize things like Script Group.

**Comment by zachsaw** [comment]
> The "TExtensionClass" parameter is making things a bit difficult, any objection to replacing it with a simple string property?

Not at all. I think it was only done this way because it was a static instance.

> Should you be able to return "null" as an IScript? Because in that case "IScriptUi" should force "TScript" to be nullable. If you don't do this it's very hard to make a general "nop" script.

Not sure if I understand this but yes you can return `null` in `CreateScript()`. `TScript` is already nullable since it has to be an `IScript`?

> It would also be nice if you could figure out a general way to get all scripts of type "TScript", that's necessary to generalize things like Script Group.

Hmm can't we just get all types that implement `IScript`?

**Comment by Shiandow** [comment]
>Not at all. I think it was only done this way because it was a static instance.

I solved it a different way ([see here](https://github.com/Shiandow/MPDN_Extensions/commit/facbd77d8409b75a30a8da10422bc7070f5a38ca)) for now, but I'm not too sure about it. It works though.

>Not sure if I understand this but yes you can return null in CreateScript(). TScript is already nullable since it has to be an IScript?

Turns out it isn't too important, It's enough to require "TScript" to be a nullable type for the ChainUi class. It would be slightly more consistent if "IScriptUi" required the same, but that's not necessary.

>Hmm can't we just get all types that implement IScript?

You could, but currently you have "Extension.RenderScripts", and "Extension.AudioScripts", and it would be nice if there was an "Extension.Scripts" that combined both, to avoid having to search literally all types.

**Comment by zachsaw** [comment]
> You could, but currently you have "Extension.RenderScripts", and "Extension.AudioScripts", and it would be nice if there was an "Extension.Scripts" that combined both, to avoid having to search literally all types.

Wouldn't this do the trick? 
`Extension.RenderScripts.Concat(Extension.AudioScripts.Cast<IExtensionUi>());`

**Comment by Shiandow** [comment]
Well, I suppose it would, but it isn't exactly pretty. Something like:

    var Scripts = Extension.Scripts.Where(script => script is IChainUi<T, TScript>);

would look a lot nicer IMO.

**Comment by zachsaw** [comment]
I meant just add the following in Helpers.cs.

```C#
    public static class Extension
    {
        ...
        public static IExtensionUi Scripts
        {
            return Extension.RenderScripts.Concat(Extension.AudioScripts.Cast<IExtensionUi>());
        }
        ...

**Comment by Shiandow** [comment]
Oh I see, yeah that should work.

**Comment by zachsaw** [comment]
Anyway leave it to me - I'll add the property and do a bit of refactoring to move the API methods / properties out of Helpers.cs into its own file.

**Comment by zachsaw** [comment]
Just a heads up. The latest commits will require test build 3525.

**Comment by Shiandow** [comment]
Ah, I see you managed to make AudioChain a descendant of Chain<Audio>, in that case it should be reasonably straightforward to make AudioChainUi etc, descendants of ChainUi. 

Script Chain and Script Group could also easily be made into AudioChains. Not sure if the UI can be generalized; Visual Studio doesn't like parametrized UI types too much (although editing the ChainList control still works, surprisingly enough).

**Comment by Shiandow** [comment]
Oh coincidentally, you should now also be able to use the "+" notation for AudioChains.

So, you can now write something like "input + new Gargle()".

**Comment by zachsaw** [comment]
Yeah I did notice it when I was working on AudioChain. It shouldn't be too hard to generalize ScriptedRenderChain now.

The VS designer doesn't like instantiated parameterized UserControl indeed. However, if you make an 'alias' class that specializes the generic class, it'll work just fine.

**Comment by Shiandow** [comment]
Weirdly enough the designer works just fine for the parametrized ChainList control, didn't expect that to work at all.

**Comment by zachsaw** [comment]
Yeah I was very surprised too, especially when the Script Chain form failed to load when I tried to open it. It's good that the designer is happy with a UserControl being parameterized. Specializing it to be instantiated by the designer is easy. Would've been trickier the other way around.

**Comment by Shiandow** [comment]
Makes me wonder if it's possible to generalize the Script Chain and Script Group Uis, but then you might run into problems that you can't really specialize the ChainList control.

**Comment by zachsaw** [comment]
Worst case scenario, we instantiate ChainList via reflection at runtime and simply put a panel in its place at designtime. Not ideal and perhaps a little awkward but should still be doable.

**Comment by Shiandow** [comment]
We could create a parameterless ChainList, and simply override all it's (public) methods in the parametrized ChainList. Then we can use the unparametrized version for design purposes, and replace it in specialized classes.

**Comment by zachsaw** [comment]
Yeah that sounds like a better idea.

**Comment by Shiandow** [comment]
Hmm, it's slightly complicated because we can't implement properties like "PresetList" in the unparametrized version. But since you only need those for the implementation you can just use the same trick for UIs that use the ChainList.

**Comment by Shiandow** [comment]
Might become a bit messy, but should be doable.

**Comment by zachsaw** [comment]
Just had another look at the Script Chain and Script Group UIs, they actually don't seem to have a lot of other controls. `RenderChainList` already encapsulates most of their functionalities so I'm wondering if we need to generalize the ConfigDialogs at all.

The only thing I might add to `RenderChainList` is the HotKeyBox, which could then be hidden via a designer-visible property. Then you're left with just the two buttons (OK and Cancel).

**Comment by Shiandow** [comment]
Might be worth a try to see if we can generalize them though, just in case we ever want to do something more complicated. But yeah, doing so would mainly be for aesthetic reasons.

**Comment by zachsaw** [comment]
If we generalize them at the expense of `RenderChainList` becoming convoluted, I'd say it's probably not worth it? Anyway give it a go and see what you end up with. Would be interesting to see what we could get away with :)

**Comment by Shiandow** [comment]
I'll give it a go when I have some time. How messy it will be will largely depend on how easy it is to swap out the ChainList control.

**Comment by zachsaw** [comment]
I suppose we should go with the straightforward method first. It's really easy now to make an Audio Script Chain and Audio Script Group. We still have Conditionals and ScriptedRenderChains etc to generalize, although I have a feeling they don't need much work at all.

**Comment by Shiandow** [comment]
Well, some work will be needed to make sure Conditionals and ScriptedRenderChains have access to the right parameters. Doesn't make much sense to conditionally change Audio Processing depending in the video size.

**Comment by zachsaw** [comment]
Yeah that seems to be the only thing that is different for Audio Processing.
Anyway, I'm going to call it a night!
Have a good day mate.

**Comment by Shiandow** [comment]
Cheers!

**Comment by Shiandow** [comment]
I think this is more or less done now isn't it?
