### ISSUE TITLE
Default installer options

### ISSUE THREAD

**Issue by Ryrynz** [zachsaw/MPDN_Extensions#171]
ATM the installer has XYSubfilter, MPC audio renderer and Sanear selected regardless of whether they're already registered on the system. LAV filters is not selected regardless of whether it's installed or not. Perhaps Full install, Minimal, and Custom presets could be used and remembered instead of detecting the registration of the filters.

**Comment by zachsaw** [comment]
I don't think this belongs here - MPDN Extensions Installer does not install any filters.
I know MPDN itself doesn't have a tracking system yet but I just haven't got any time to do it.
@Belphemur Could we run an issue tracking system on your server too?

**Comment by zachsaw** [comment]
BTW, the reason the installer forces an overwrite is because it currently doesn't know what version is installed. If the installer has a newer version bundled, it should overwrite the existing filters automatically.

**Comment by Ryrynz** [comment]
Yeah, really have no other place to put this so hence it's here. Yeah that'd be good if the filters were updated on the system.  If the filters were installed in a program files directory then they should be updated there. ATM we're only getting installs into MPDN's filters directory.

**Comment by Belphemur** [comment]
@zachsaw I'll install one when I have the time. I'm in a moving 
(changing country right now).
