### ISSUE TITLE
Big wish: Please improve Deband filter even further

### ISSUE THREAD

**Issue by aufkrawall** [zachsaw/MPDN_Extensions#176]
I already really like the deband filter, can't imagine to use MPDN without it.
However, it would be great if it could be improved further. I personally still like the madVR deband filter more, as it can fight banding in some areas better (I think mostly when the banding doesn't come with blocking).
Thanks a lot for your efforts, Shiandow. :)

**Comment by aufkrawall** [comment]
lol!
I didn't know that "big wish" is a common category for classifying issues. :p

**Comment by Shiandow** [comment]
Closed in #233.
