### ISSUE TITLE
Opensubtitles messagebox is annoying

### ISSUE THREAD

**Issue by TheRealMarnes** [zachsaw/MPDN_Extensions#44]
On line 71 in https://github.com/zachsaw/MPDN_Extensions/blob/master/Extensions/PlayerExtensions/OpenSubtitles.PlayerExtension.cs a messagebox is triggered to tell the user if no subtitles were found. Please add a checkbox to the extension's config that allows the user to disable the messagebox and let the lack of subtitles go by quietly. Watching anything that isn't a mainstream video becomes really annoying if you also want the automatic subtitles when you do watch a mainstream video file.

**Comment by zachsaw** [comment]
Easy change but yes I agree.
I think I'll get rid of that message box altogether.

**Comment by TheRealMarnes** [comment]
Awesome, thanks

**Comment by zachsaw** [comment]
Fixed in master. Will be available in next release.

**Comment by TheRealMarnes** [comment]
Fixed in master, but the source file still clearly shows it at line 85 and there have been 2 updates already that still have this messagebox... ?

**Comment by zachsaw** [comment]
Line 85 only triggers if there's an exception. Your issue was with line 71 (as you've said in your original post) wasn't it?

**Comment by TheRealMarnes** [comment]
Aaahh, right, I see. My bad, sorry. All is well :)
