### ISSUE TITLE
OpenSubtitle: Option to disable download if sub of certain language is already available

### ISSUE THREAD

**Issue by zachsaw** [zachsaw/MPDN_Extensions#49]
Currently the open subtitle extension displays a list of subs even if the one we're interested in is already downloaded - e.g. English. It would be good to have an option to disable this prompt when the sub of the language of user's choice is already available.

**Comment by zachsaw** [comment]
@Belphemur Can you take a look at this please?

**Comment by Belphemur** [comment]
You can assign it to me. I'll check that in the following week. 

On 20 June 2015 07:44:27 CEST, Zach Saw <notifications@github.com> wrote:
>@Belphemur Can you take a look at this please?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zachsaw/MPDN_Extensions/issues/49#issuecomment-113712941

-- 
Best Regards, 
Antoine Aflalo

**Comment by Belphemur** [comment]
I have a quick fix ready for this using the prefered language. But I want to be able to do more than this.

Can you brief me how I can register new subtitile using the DirectVobSub interface  ([Like Described here](https://github.com/Cyberbeing/xy-VSFilter/blob/master/src/filters/transform/vsfilter/IDirectVobSub.h)).

I'm appending the language to the subtitle, VSFilter can detect those file and load them, but they aren't loaded in the Subtitle menu of MPDN. I would really like to have an access to this interface to be able to feed subtitle dynamically to the interface as MPC-HC is doing. This way, no need for MediaLoading but ONLY when the user press a key (or shortcut, or menu).

**Comment by zachsaw** [comment]
MPDN doesn't support the DirectVobSub interface... yet. So the only way you can load additional subtitles is externally at the moment.

**Comment by Belphemur** [comment]
How does MPDN populate the subtitles menu ?
If it's done by scanning, the directory, you could add the Format:
```
MediaFileName.Lang.srt
```
And use the Lang as the Title of the Subtitle.

**Comment by zachsaw** [comment]
It populates it with whatever DirectShow tells it, and these external subs
only get loaded once when you load a media file.
