### ISSUE TITLE
Line Endings

### ISSUE THREAD

**Issue by Belphemur** [zachsaw/MPDN_Extensions#50]
Hello Zach,

I have again a problem with the line ending with all the file you modified/added.
It would guess it's a conflict between svn/git. 
Are you using git or svn for this repository ?

**Comment by zachsaw** [comment]
No I've switched to git. Are you still getting this problem?

**Comment by Belphemur** [comment]
I don't understand where it's coming from. For now I removed the conflicted files and checkout. Only the AssemblyInfo is still a problem. 

On 22 June 2015 01:57:33 CEST, Zach Saw <notifications@github.com> wrote:
>No I've switched to git. Are you still getting this problem?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/zachsaw/MPDN_Extensions/issues/50#issuecomment-113970720

-- 
Best Regards, 
Antoine Aflalo

**Comment by zachsaw** [comment]
I think you can ignore AssemblyInfo.cs as it gets regenerated each time you
run/build.
