### ISSUE TITLE
Make Video Letter Boxing available in menus

### ISSUE THREAD

**Issue by zachsaw** [zachsaw/MPDN_Extensions#85]
There's been requests for the "Video Letter Boxing" option accessible via Video Renderer -> Composition to be accessible via context menu so an extension would be the perfect place to do this. Also add hotkeys to allow user to cycle through the various options (see RendererControl.cs for example).

**Comment by Garteal** [comment]
This isn't exposed yet is it?

**Comment by zachsaw** [comment]
I think it is via the PlayerConfig property.
