### ISSUE TITLE
[RendererControl] Add support for Chroma Reconstruction

### ISSUE THREAD

**Issue by Shiandow** [zachsaw/MPDN_Extensions#86]
Since it's enabled by default it might be good idea to also add a way to toggle it when necessary to make troubleshooting easier.

**Comment by zachsaw** [comment]
Good idea. Assigning it to you :)

**Comment by Shiandow** [comment]
While we're on this subject anyway. Can anyone think of a better way to temporarily change the settings? With the current method it also resets when it needs to reset the rendering *for any reason*, including when you use a hotkey to toggle a Script Group.

In fact it's partially luck that it's even possible to change the colour space and range at the same time.

**Comment by zachsaw** [comment]
Can't remember if there's a PlayerSettingsChanged event but if there is we could save the existing settings in the media closed and settings changed events and restore them in the media closed event. Then when a hot key is applied, simply commit the settings.

**Comment by zachsaw** [comment]
Just checked. There's indeed Config.Changed event that you could use to do that.

**Comment by Shiandow** [comment]
I can think of one problem with that though, it would mean that the 'temporary' settings would become final if the user opens the settings dialog, changes something irrelevant, and then closes it again. The settings would need to be switched back before the dialog is opened.

The most robust solution might be to add setters to "Renderer.Colorimetric" and "Renderer.LimitChroma" and reset those to the defaults when a new file is opened.

**Comment by zachsaw** [comment]
Hmm... What if we stay with the current method and just reapply the temporary settings in the Player.Config.Changed event? That would work well wouldn't it? Selecting the scripts via hotkeys triggers the event too.

Introducing properties already accessible via player's config not only makes it confusing but also seems like a full duplication of the config properties except they're temporary.

**Comment by Shiandow** [comment]
You'll still need 1 more event I think. Since there's no way of telling when the settings can be changed back. Calling Config.Refresh() is not an option.

**Comment by zachsaw** [comment]
I've implemented this and made YUV / level toggle consistent with what's being shown in the options dialog too. The original settings only gets restored when media is closed. The original settings also get overwritten when user changes the settings explicitly via the options dialog.
