### ISSUE TITLE
Allow users to selectively disable extensions

### ISSUE THREAD

**Issue by Ryrynz** [zachsaw/MPDN_Extensions#96]
This would reduce the start up time by a small margin.
The installer would have to respect these settings when updating.

**Comment by zachsaw** [comment]
Profiling MPDN startup time revealed the playlist to take most of the time... The only way to reduce startup time would be to remove the playlist extension which wouldn't be ideal at all...

**Comment by Ryrynz** [comment]
Definitely not. Good to know though.

**Comment by zachsaw** [comment]
I did find that adding menu items to the toolstrip (main menu bar) actually cost a fair bit of time. In fact, it's around 250ms on my PC. I'll see if I could do something like http://stackoverflow.com/questions/19682304/in-a-winforms-menu-is-there-a-way-to-batch-update to make it faster... Looking at the answer of that question, it's 48ms to add 1000 menu items.

With the bulk of the time still being spent on loading and initializing the playlist, it might be worth getting @Garteal to profile the playlist extension. In particular, both the constructor (playlist form c'tor) and the Initialize method takes a fair bit of time. Perhaps we could create resources only when we need them, that might split the cost up so it doesn't feel so slow when it starts up.

**Comment by zachsaw** [comment]
I've managed to get rid of the 250ms entirely! Now the only thing left is the constructor and initialize() method of playlist.

**Comment by Ryrynz** [comment]
Great work, can't wait to see the results.

**Comment by Garteal** [comment]
Something introduced a nullpointer exception with whatever changes you made @zachsaw when you have the playlist set to show on startup. I'll fix it though.
