### ISSUE TITLE
NNEDI3: option for separate neuron settings for each pass

### ISSUE THREAD

**Issue by aufkrawall** [zachsaw/MPDN_Extensions#99]
It can make sense to do the first pass with more neurons than with the second one to achieve a better result. Therefore, an option to set this up would be nice.

**Comment by zachsaw** [comment]
Done!

https://github.com/zachsaw/MPDN_Extensions/compare/fe9cb8fa926a228da78caf20bf190c2a8149588f...46bd8205194e0be45ac06e868333fd04bf8af063
